# Generated by Django 5.2.9 on 2025-12-09 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "db_table": "auth_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroupPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_group_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("codename", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "auth_permission",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.IntegerField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.IntegerField()),
                ("is_active", models.IntegerField()),
                ("date_joined", models.DateTimeField()),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserGroups",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserUserPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_user_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoAdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_time", models.DateTimeField()),
                ("object_id", models.TextField(blank=True, null=True)),
                ("object_repr", models.CharField(max_length=200)),
                ("action_flag", models.PositiveSmallIntegerField()),
                ("change_message", models.TextField()),
            ],
            options={
                "db_table": "django_admin_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "django_content_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoMigrations",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("app", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("applied", models.DateTimeField()),
            ],
            options={
                "db_table": "django_migrations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("session_data", models.TextField()),
                ("expire_date", models.DateTimeField()),
            ],
            options={
                "db_table": "django_session",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Subscriptionplans",
            fields=[
                (
                    "subscriptionplanid",
                    models.AutoField(
                        db_column="SubscriptionPlanID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_column="Name", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, db_column="Description", null=True),
                ),
                (
                    "monthlyprice",
                    models.DecimalField(
                        db_column="MonthlyPrice", decimal_places=2, max_digits=10
                    ),
                ),
                (
                    "yearlyprice",
                    models.DecimalField(
                        db_column="YearlyPrice", decimal_places=2, max_digits=10
                    ),
                ),
                (
                    "max_exchanges",
                    models.IntegerField(db_column="MaxExchanges", default=1),
                ),
                (
                    "max_api_calls_per_hour",
                    models.IntegerField(db_column="MaxAPICallsPerHour", default=100),
                ),
                (
                    "ai_predictions_enabled",
                    models.BooleanField(
                        db_column="AIPredictionsEnabled", default=False
                    ),
                ),
                (
                    "advanced_indicators_enabled",
                    models.BooleanField(
                        db_column="AdvancedIndicatorsEnabled", default=False
                    ),
                ),
                (
                    "portfolio_tracking",
                    models.BooleanField(db_column="PortfolioTracking", default=False),
                ),
                (
                    "trade_automation",
                    models.BooleanField(db_column="TradeAutomation", default=False),
                ),
                ("featuredetails", models.TextField(db_column="FeatureDetails")),
                ("isactive", models.IntegerField(blank=True, null=True)),
                ("isdeleted", models.IntegerField(blank=True, null=True)),
                (
                    "createdby",
                    models.IntegerField(blank=True, db_column="CreatedBy", null=True),
                ),
                (
                    "updatedby",
                    models.IntegerField(blank=True, db_column="UpdatedBy", null=True),
                ),
                (
                    "createdat",
                    models.DateTimeField(blank=True, db_column="CreatedAt", null=True),
                ),
                (
                    "updatedat",
                    models.DateTimeField(blank=True, db_column="UpdatedAt", null=True),
                ),
            ],
            options={
                "db_table": "SubscriptionPlans",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="WorkerShard",
            fields=[
                (
                    "shardid",
                    models.AutoField(
                        db_column="ShardID", primary_key=True, serialize=False
                    ),
                ),
                ("shard_name", models.CharField(db_column="ShardName", max_length=50)),
                ("worker_id", models.CharField(db_column="WorkerID", max_length=100)),
                (
                    "assigned_series",
                    models.JSONField(db_column="AssignedSeries", default=list),
                ),
                (
                    "status",
                    models.CharField(db_column="Status", default="idle", max_length=20),
                ),
                (
                    "last_heartbeat",
                    models.DateTimeField(auto_now=True, db_column="LastHeartbeat"),
                ),
                (
                    "series_count",
                    models.IntegerField(db_column="SeriesCount", default=0),
                ),
                (
                    "backfill_progress",
                    models.FloatField(db_column="BackfillProgress", default=0.0),
                ),
                ("isactive", models.IntegerField(db_column="IsActive", default=1)),
                ("isdeleted", models.IntegerField(db_column="IsDeleted", default=0)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="UpdatedAt"),
                ),
            ],
            options={
                "db_table": "WorkerShards",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Exchange",
            fields=[
                (
                    "exchangeid",
                    models.AutoField(
                        db_column="ExchangeID", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="Name", max_length=50)),
                (
                    "display_name",
                    models.CharField(db_column="DisplayName", max_length=100),
                ),
                (
                    "market_type",
                    models.CharField(
                        blank=True, db_column="MarketType", max_length=20, null=True
                    ),
                ),
                (
                    "isactive",
                    models.IntegerField(blank=True, db_column="IsActive", null=True),
                ),
                (
                    "isdeleted",
                    models.IntegerField(blank=True, db_column="IsDeleted", null=True),
                ),
                (
                    "createdby",
                    models.IntegerField(blank=True, db_column="CreatedBy", null=True),
                ),
                (
                    "updatedby",
                    models.IntegerField(blank=True, db_column="UpdatedBy", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="UpdatedAt"),
                ),
            ],
            options={
                "db_table": "Exchanges",
                "managed": True,
                "unique_together": {("name", "market_type")},
            },
        ),
        migrations.CreateModel(
            name="Trendinghashtag",
            fields=[
                (
                    "trendinghashtagid",
                    models.AutoField(
                        db_column="TrendingHashtagID", primary_key=True, serialize=False
                    ),
                ),
                ("hashtag", models.CharField(db_column="Hashtag", max_length=100)),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, db_column="Timestamp"),
                ),
                ("count_1h", models.IntegerField(db_column="Count1H", default=0)),
                ("count_6h", models.IntegerField(db_column="Count6H", default=0)),
                ("count_24h", models.IntegerField(db_column="Count24H", default=0)),
                ("velocity", models.FloatField(db_column="Velocity", default=0.0)),
                (
                    "avg_sentiment",
                    models.FloatField(db_column="AvgSentiment", default=0.0),
                ),
                ("trend_score", models.FloatField(db_column="TrendScore", default=0.0)),
            ],
            options={
                "db_table": "TrendingHashtags",
                "ordering": ["-timestamp"],
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["hashtag", "timestamp"],
                        name="TrendingHas_Hashtag_875b43_idx",
                    ),
                    models.Index(
                        fields=["trend_score", "timestamp"],
                        name="TrendingHas_TrendSc_06ca92_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Trendingkeyword",
            fields=[
                (
                    "trendingkeywordid",
                    models.AutoField(
                        db_column="TrendingKeywordID", primary_key=True, serialize=False
                    ),
                ),
                ("keyword", models.CharField(db_column="Keyword", max_length=100)),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, db_column="Timestamp"),
                ),
                ("count_1h", models.IntegerField(db_column="Count1H", default=0)),
                ("count_6h", models.IntegerField(db_column="Count6H", default=0)),
                ("count_24h", models.IntegerField(db_column="Count24H", default=0)),
                ("velocity", models.FloatField(db_column="Velocity", default=0.0)),
                (
                    "avg_sentiment",
                    models.FloatField(db_column="AvgSentiment", default=0.0),
                ),
                ("sources", models.JSONField(db_column="Sources", default=dict)),
            ],
            options={
                "db_table": "TrendingKeywords",
                "ordering": ["-timestamp"],
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["keyword", "timestamp"],
                        name="TrendingKey_Keyword_b82802_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Trendingtopic",
            fields=[
                (
                    "trendingtopicid",
                    models.AutoField(
                        db_column="TrendingTopicID", primary_key=True, serialize=False
                    ),
                ),
                ("topic_id", models.IntegerField(db_column="TopicID")),
                ("topic_name", models.CharField(db_column="TopicName", max_length=255)),
                ("keywords", models.JSONField(db_column="Keywords", default=list)),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, db_column="Timestamp"),
                ),
                (
                    "document_count",
                    models.IntegerField(db_column="DocumentCount", default=0),
                ),
                ("velocity", models.FloatField(db_column="Velocity", default=0.0)),
                (
                    "avg_sentiment",
                    models.FloatField(db_column="AvgSentiment", default=0.0),
                ),
                ("is_spike", models.BooleanField(db_column="IsSpike", default=False)),
            ],
            options={
                "db_table": "TrendingTopics",
                "ordering": ["-timestamp"],
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["topic_id", "timestamp"],
                        name="TrendingTop_TopicID_711f08_idx",
                    ),
                    models.Index(
                        fields=["is_spike", "timestamp"],
                        name="TrendingTop_IsSpike_9a9981_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "userid",
                    models.AutoField(
                        db_column="UserID", primary_key=True, serialize=False
                    ),
                ),
                ("fullname", models.CharField(db_column="FullName", max_length=255)),
                (
                    "email",
                    models.CharField(db_column="Email", max_length=255, unique=True),
                ),
                (
                    "passwordhash",
                    models.CharField(db_column="PasswordHash", max_length=255),
                ),
                ("role", models.CharField(db_column="Role", max_length=12)),
                (
                    "organization",
                    models.CharField(
                        blank=True, db_column="Organization", max_length=255, null=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, db_column="Phone", max_length=20, null=True
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, db_column="Address", null=True),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, db_column="State", max_length=45, null=True
                    ),
                ),
                (
                    "zipcode",
                    models.CharField(
                        blank=True, db_column="ZipCode", max_length=45, null=True
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, db_column="Country", max_length=45, null=True
                    ),
                ),
                (
                    "logo_path",
                    models.CharField(
                        blank=True, db_column="LogoPath", max_length=500, null=True
                    ),
                ),
                (
                    "useusersmtp",
                    models.IntegerField(
                        blank=True, db_column="UseCustomSMTP", null=True
                    ),
                ),
                (
                    "smtphost",
                    models.CharField(
                        blank=True, db_column="SMTPHost", max_length=255, null=True
                    ),
                ),
                (
                    "smtpport",
                    models.IntegerField(blank=True, db_column="SMTPPort", null=True),
                ),
                (
                    "smtphostuser",
                    models.CharField(
                        blank=True, db_column="SMTPHostUser", max_length=255, null=True
                    ),
                ),
                (
                    "smtphostpassword",
                    models.CharField(
                        blank=True,
                        db_column="SMTPHostPassword",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "smtpusetls",
                    models.IntegerField(blank=True, db_column="SMTPUseTLS", null=True),
                ),
                (
                    "trading_experience",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        db_column="TradingExperience",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "risk_tolerance",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        db_column="RiskTolerance",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("isactive", models.IntegerField(blank=True, null=True)),
                ("isdeleted", models.IntegerField(blank=True, null=True)),
                (
                    "createdby",
                    models.IntegerField(blank=True, db_column="CreatedBy", null=True),
                ),
                (
                    "updatedby",
                    models.IntegerField(blank=True, db_column="UpdatedBy", null=True),
                ),
                (
                    "createdat",
                    models.DateTimeField(blank=True, db_column="CreatedAt", null=True),
                ),
                (
                    "updatedat",
                    models.DateTimeField(blank=True, db_column="UpdatedAt", null=True),
                ),
            ],
            options={
                "db_table": "Users",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["email", "isactive"], name="Users_Email_b4355d_idx"
                    ),
                    models.Index(
                        fields=["role", "isactive"], name="Users_Role_bf87e6_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Subscriptions",
            fields=[
                (
                    "subscriptionid",
                    models.AutoField(
                        db_column="SubscriptionID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "billingfrequency",
                    models.CharField(
                        choices=[
                            ("Monthly", "Monthly"),
                            ("Yearly", "Yearly"),
                            ("Weekly", "Weekly"),
                            ("Semi-Annually", "Semi-Annually"),
                            ("Quarterly", "Quarterly"),
                            ("One-Time", "One-Time"),
                            ("Other", "Other"),
                        ],
                        db_column="BillingFrequency",
                        max_length=13,
                    ),
                ),
                ("startdate", models.DateField(db_column="StartDate")),
                ("enddate", models.DateField(db_column="EndDate")),
                ("autorenew", models.IntegerField(db_column="AutoRenew")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Expired", "Expired"),
                            ("Cancelled", "Cancelled"),
                            ("Pending", "Pending"),
                            ("Suspended", "Suspended"),
                            ("RenewalPending", "RenewalPending"),
                            ("Trial", "Trial"),
                        ],
                        db_column="Status",
                        max_length=14,
                    ),
                ),
                (
                    "renewalcount",
                    models.IntegerField(
                        blank=True, db_column="RenewalCount", null=True
                    ),
                ),
                (
                    "lastrenewedat",
                    models.DateTimeField(
                        blank=True, db_column="LastRenewedAt", null=True
                    ),
                ),
                ("isactive", models.IntegerField(blank=True, null=True)),
                ("isdeleted", models.IntegerField(blank=True, null=True)),
                (
                    "createdby",
                    models.IntegerField(blank=True, db_column="CreatedBy", null=True),
                ),
                (
                    "updatedby",
                    models.IntegerField(blank=True, db_column="UpdatedBy", null=True),
                ),
                (
                    "createdat",
                    models.DateTimeField(blank=True, db_column="CreatedAt", null=True),
                ),
                (
                    "updatedat",
                    models.DateTimeField(blank=True, db_column="UpdatedAt", null=True),
                ),
                (
                    "subscriptionplanid",
                    models.ForeignKey(
                        blank=True,
                        db_column="SubscriptionPlanID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.subscriptionplans",
                    ),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        blank=True,
                        db_column="UserID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.users",
                    ),
                ),
            ],
            options={
                "db_table": "Subscriptions",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Renewals",
            fields=[
                (
                    "renewalid",
                    models.AutoField(
                        db_column="RenewalID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "renewaldate",
                    models.DateTimeField(
                        blank=True, db_column="RenewalDate", null=True
                    ),
                ),
                (
                    "renewalcost",
                    models.DecimalField(
                        db_column="RenewalCost", decimal_places=2, max_digits=10
                    ),
                ),
                ("notes", models.TextField(blank=True, db_column="Notes", null=True)),
                (
                    "isactive",
                    models.IntegerField(blank=True, db_column="IsActive", null=True),
                ),
                (
                    "isdeleted",
                    models.IntegerField(blank=True, db_column="IsDeleted", null=True),
                ),
                (
                    "createdat",
                    models.DateTimeField(blank=True, db_column="CreatedAt", null=True),
                ),
                (
                    "updatedat",
                    models.DateTimeField(blank=True, db_column="UpdatedAt", null=True),
                ),
                (
                    "subscriptionid",
                    models.ForeignKey(
                        blank=True,
                        db_column="SubscriptionID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.subscriptions",
                    ),
                ),
                (
                    "renewedby",
                    models.ForeignKey(
                        blank=True,
                        db_column="RenewedBy",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.users",
                    ),
                ),
            ],
            options={
                "db_table": "Renewals",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Reminders",
            fields=[
                (
                    "reminderid",
                    models.AutoField(
                        db_column="ReminderID", primary_key=True, serialize=False
                    ),
                ),
                ("note", models.TextField(blank=True, db_column="Note", null=True)),
                ("timestamp", models.DateTimeField(db_column="Timestamp")),
                ("isactive", models.IntegerField(blank=True, null=True)),
                ("isdeleted", models.IntegerField(blank=True, null=True)),
                (
                    "createdby",
                    models.IntegerField(blank=True, db_column="CreatedBy", null=True),
                ),
                (
                    "updatedby",
                    models.IntegerField(blank=True, db_column="UpdatedBy", null=True),
                ),
                (
                    "createdat",
                    models.DateTimeField(blank=True, db_column="CreatedAt", null=True),
                ),
                (
                    "updatedat",
                    models.DateTimeField(blank=True, db_column="UpdatedAt", null=True),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        blank=True,
                        db_column="UserID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.users",
                    ),
                ),
            ],
            options={
                "db_table": "Reminders",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "notificationid",
                    models.AutoField(
                        db_column="NotificationID", primary_key=True, serialize=False
                    ),
                ),
                ("title", models.TextField(db_column="Title")),
                ("message", models.TextField(db_column="Message")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Expiry", "Expiry"),
                            ("Renewal", "Renewal"),
                            ("System", "System"),
                        ],
                        db_column="Type",
                        max_length=7,
                    ),
                ),
                (
                    "isread",
                    models.IntegerField(blank=True, db_column="IsRead", null=True),
                ),
                ("isactive", models.IntegerField(blank=True, null=True)),
                ("isdeleted", models.IntegerField(blank=True, null=True)),
                (
                    "createdby",
                    models.IntegerField(blank=True, db_column="CreatedBy", null=True),
                ),
                (
                    "updatedby",
                    models.IntegerField(blank=True, db_column="UpdatedBy", null=True),
                ),
                (
                    "createdat",
                    models.DateTimeField(blank=True, db_column="CreatedAt", null=True),
                ),
                (
                    "updatedat",
                    models.DateTimeField(blank=True, db_column="UpdatedAt", null=True),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        blank=True,
                        db_column="UserID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.users",
                    ),
                ),
            ],
            options={
                "db_table": "Notifications",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Monthlyanalytics",
            fields=[
                (
                    "analyticsid",
                    models.AutoField(
                        db_column="AnalyticsID", primary_key=True, serialize=False
                    ),
                ),
                ("year", models.IntegerField(db_column="Year")),
                ("month", models.IntegerField(db_column="Month")),
                (
                    "renewals",
                    models.IntegerField(blank=True, db_column="Renewals", null=True),
                ),
                (
                    "cancellations",
                    models.IntegerField(
                        blank=True, db_column="Cancellations", null=True
                    ),
                ),
                (
                    "newsubscriptions",
                    models.IntegerField(
                        blank=True, db_column="NewSubscriptions", null=True
                    ),
                ),
                (
                    "totalpayments",
                    models.DecimalField(
                        blank=True,
                        db_column="TotalPayments",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("isactive", models.IntegerField(blank=True, null=True)),
                ("isdeleted", models.IntegerField(blank=True, null=True)),
                (
                    "createdat",
                    models.DateTimeField(blank=True, db_column="CreatedAt", null=True),
                ),
                (
                    "updatedat",
                    models.DateTimeField(blank=True, db_column="UpdatedAt", null=True),
                ),
                (
                    "createdby",
                    models.IntegerField(blank=True, db_column="CreatedBy", null=True),
                ),
                (
                    "updatedby",
                    models.IntegerField(blank=True, db_column="UpdatedBy", null=True),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        blank=True,
                        db_column="UserID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.users",
                    ),
                ),
            ],
            options={
                "db_table": "MonthlyAnalytics",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "eventid",
                    models.AutoField(
                        db_column="EventID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Action", "Action"), ("Reminder", "Reminder")],
                        db_column="Type",
                        max_length=8,
                    ),
                ),
                ("title", models.TextField(db_column="Title")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Personal", "Personal"),
                            ("Work", "Work"),
                            ("Birthday", "Birthday"),
                            ("Deadline", "Deadline"),
                            ("Other", "Other"),
                        ],
                        db_column="Category",
                        max_length=8,
                    ),
                ),
                ("starttime", models.TimeField(db_column="StartTime")),
                ("endtime", models.TimeField(db_column="EndTime")),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="Location", max_length=255, null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, db_column="Description", null=True),
                ),
                ("repeated", models.IntegerField(db_column="Repeated")),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Daily", "Daily"),
                            ("Weekly", "Weekly"),
                            ("Monthly", "Monthly"),
                            ("Yearly", "Yearly"),
                        ],
                        db_column="Frequency",
                        max_length=7,
                        null=True,
                    ),
                ),
                ("startdate", models.DateField(db_column="StartDate")),
                (
                    "enddate",
                    models.DateField(blank=True, db_column="EndDate", null=True),
                ),
                ("emailto", models.TextField(db_column="EmailTo")),
                (
                    "emailcc",
                    models.TextField(blank=True, db_column="EmailCC", null=True),
                ),
                (
                    "emailsubject",
                    models.TextField(blank=True, db_column="EmailSubject", null=True),
                ),
                (
                    "emailbody",
                    models.TextField(blank=True, db_column="EmailBody", null=True),
                ),
                ("isactive", models.IntegerField(blank=True, null=True)),
                ("isdeleted", models.IntegerField(blank=True, null=True)),
                (
                    "createdby",
                    models.IntegerField(blank=True, db_column="CreatedBy", null=True),
                ),
                (
                    "updatedby",
                    models.IntegerField(blank=True, db_column="UpdatedBy", null=True),
                ),
                (
                    "createdat",
                    models.DateTimeField(blank=True, db_column="CreatedAt", null=True),
                ),
                (
                    "updatedat",
                    models.DateTimeField(blank=True, db_column="UpdatedAt", null=True),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        blank=True,
                        db_column="UserID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.users",
                    ),
                ),
            ],
            options={
                "db_table": "Events",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Auditlogs",
            fields=[
                (
                    "auditlogid",
                    models.AutoField(
                        db_column="AuditLogID", primary_key=True, serialize=False
                    ),
                ),
                ("action", models.CharField(db_column="Action", max_length=255)),
                (
                    "tableaffected",
                    models.CharField(
                        blank=True, db_column="TableAffected", max_length=255, null=True
                    ),
                ),
                (
                    "recordid",
                    models.IntegerField(blank=True, db_column="RecordID", null=True),
                ),
                ("createdat", models.DateTimeField(db_column="CreatedAt")),
                (
                    "createdby",
                    models.IntegerField(blank=True, db_column="CreatedBy", null=True),
                ),
                ("isactive", models.IntegerField(blank=True, null=True)),
                ("isdeleted", models.IntegerField(blank=True, null=True)),
                ("updatedat", models.DateTimeField(db_column="UpdatedAt")),
                (
                    "updatedby",
                    models.IntegerField(blank=True, db_column="UpdatedBy", null=True),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        blank=True,
                        db_column="UserID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.users",
                    ),
                ),
            ],
            options={
                "db_table": "AuditLogs",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="APIUsage",
            fields=[
                (
                    "apiusageid",
                    models.AutoField(
                        db_column="APIUsageID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "endpoint_type",
                    models.CharField(db_column="EndpointType", max_length=50),
                ),
                (
                    "request_count",
                    models.IntegerField(db_column="RequestCount", default=1),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, db_column="Timestamp"),
                ),
                (
                    "isactive",
                    models.IntegerField(blank=True, db_column="IsActive", null=True),
                ),
                (
                    "isdeleted",
                    models.IntegerField(blank=True, db_column="IsDeleted", null=True),
                ),
                (
                    "exchange",
                    models.ForeignKey(
                        db_column="ExchangeID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.exchange",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="UserID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.users",
                    ),
                ),
            ],
            options={
                "db_table": "APIUsage",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Activitylogs",
            fields=[
                (
                    "activityid",
                    models.AutoField(
                        db_column="ActivityID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "activitytype",
                    models.CharField(db_column="ActivityType", max_length=18),
                ),
                (
                    "activitydetails",
                    models.TextField(
                        blank=True, db_column="ActivityDetails", null=True
                    ),
                ),
                (
                    "activitydate",
                    models.DateTimeField(
                        blank=True, db_column="ActivityDate", null=True
                    ),
                ),
                ("isactive", models.IntegerField(blank=True, null=True)),
                ("isdeleted", models.IntegerField(blank=True, null=True)),
                (
                    "createdat",
                    models.DateTimeField(blank=True, db_column="CreatedAt", null=True),
                ),
                (
                    "updatedat",
                    models.DateTimeField(blank=True, db_column="UpdatedAt", null=True),
                ),
                (
                    "createdby",
                    models.IntegerField(blank=True, db_column="CreatedBy", null=True),
                ),
                (
                    "updatedby",
                    models.IntegerField(blank=True, db_column="UpdatedBy", null=True),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        blank=True,
                        db_column="UserID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.users",
                    ),
                ),
            ],
            options={
                "db_table": "ActivityLogs",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UserTrade",
            fields=[
                (
                    "tradeid",
                    models.AutoField(
                        db_column="TradeID", primary_key=True, serialize=False
                    ),
                ),
                ("symbol", models.CharField(db_column="Symbol", max_length=20)),
                (
                    "side",
                    models.CharField(
                        choices=[("buy", "Buy"), ("sell", "Sell")],
                        db_column="Side",
                        max_length=4,
                    ),
                ),
                (
                    "trade_type",
                    models.CharField(
                        choices=[
                            ("market", "Market"),
                            ("limit", "Limit"),
                            ("stop", "Stop"),
                        ],
                        db_column="TradeType",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        db_column="Amount", decimal_places=8, max_digits=20
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        db_column="Price",
                        decimal_places=8,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "filled_amount",
                    models.DecimalField(
                        db_column="FilledAmount",
                        decimal_places=8,
                        default=0,
                        max_digits=20,
                    ),
                ),
                (
                    "filled_price",
                    models.DecimalField(
                        blank=True,
                        db_column="FilledPrice",
                        decimal_places=8,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("filled", "Filled"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        db_column="Status",
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "exchange_order_id",
                    models.CharField(
                        blank=True, db_column="ExchangeOrderID", max_length=100
                    ),
                ),
                (
                    "fees",
                    models.DecimalField(
                        db_column="Fees", decimal_places=8, default=0, max_digits=20
                    ),
                ),
                (
                    "isactive",
                    models.IntegerField(blank=True, db_column="IsActive", null=True),
                ),
                (
                    "isdeleted",
                    models.IntegerField(blank=True, db_column="IsDeleted", null=True),
                ),
                (
                    "createdby",
                    models.IntegerField(blank=True, db_column="CreatedBy", null=True),
                ),
                (
                    "updatedby",
                    models.IntegerField(blank=True, db_column="UpdatedBy", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="UpdatedAt"),
                ),
                (
                    "exchange",
                    models.ForeignKey(
                        db_column="ExchangeID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.exchange",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="UserID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.users",
                    ),
                ),
            ],
            options={
                "db_table": "UserTrades",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SeriesConfig",
            fields=[
                (
                    "seriesconfigid",
                    models.AutoField(
                        db_column="SeriesConfigID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "market_type",
                    models.CharField(db_column="MarketType", max_length=20),
                ),
                ("symbol", models.CharField(db_column="Symbol", max_length=20)),
                ("timeframe", models.CharField(db_column="Timeframe", max_length=10)),
                (
                    "earliest_start_ms",
                    models.BigIntegerField(
                        blank=True, db_column="EarliestStartMS", null=True
                    ),
                ),
                (
                    "last_backfill_ms",
                    models.BigIntegerField(
                        blank=True, db_column="LastBackfillMS", null=True
                    ),
                ),
                (
                    "last_ts_ms",
                    models.BigIntegerField(blank=True, db_column="LastTsMS", null=True),
                ),
                (
                    "probing_completed",
                    models.BooleanField(db_column="ProbingCompleted", default=False),
                ),
                (
                    "backfill_completed",
                    models.BooleanField(db_column="BackfillCompleted", default=False),
                ),
                (
                    "listing_date_ms",
                    models.BigIntegerField(
                        blank=True, db_column="ListingDateMS", null=True
                    ),
                ),
                (
                    "probe_attempts",
                    models.IntegerField(db_column="ProbeAttempts", default=0),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, db_column="LastError", null=True),
                ),
                ("isactive", models.IntegerField(db_column="IsActive", default=1)),
                ("isdeleted", models.IntegerField(db_column="IsDeleted", default=0)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="UpdatedAt"),
                ),
                (
                    "exchange",
                    models.ForeignKey(
                        db_column="ExchangeID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.exchange",
                    ),
                ),
            ],
            options={
                "db_table": "SeriesConfig",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["exchange", "market_type", "symbol", "timeframe"],
                        name="SeriesConfi_Exchang_91e86d_idx",
                    ),
                    models.Index(
                        fields=["backfill_completed"],
                        name="SeriesConfi_Backfil_160395_idx",
                    ),
                    models.Index(
                        fields=["probing_completed"],
                        name="SeriesConfi_Probing_c3ce91_idx",
                    ),
                ],
                "unique_together": {("exchange", "market_type", "symbol", "timeframe")},
            },
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "paymentid",
                    models.AutoField(
                        db_column="PaymentID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        db_column="Amount", decimal_places=2, max_digits=10
                    ),
                ),
                ("paymentdate", models.DateField(db_column="PaymentDate")),
                (
                    "paymentmethod",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CreditCard", "CreditCard"),
                            ("PayPal", "PayPal"),
                            ("BankTransfer", "BankTransfer"),
                        ],
                        db_column="PaymentMethod",
                        max_length=12,
                        null=True,
                    ),
                ),
                (
                    "referencenumber",
                    models.CharField(
                        blank=True,
                        db_column="ReferenceNumber",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                        ],
                        db_column="Status",
                        max_length=9,
                        null=True,
                    ),
                ),
                (
                    "paymentresponse",
                    models.TextField(
                        blank=True, db_column="PaymentResponse", null=True
                    ),
                ),
                ("isactive", models.IntegerField(blank=True, null=True)),
                ("isdeleted", models.IntegerField(blank=True, null=True)),
                (
                    "createdby",
                    models.IntegerField(blank=True, db_column="CreatedBy", null=True),
                ),
                (
                    "updatedby",
                    models.IntegerField(blank=True, db_column="UpdatedBy", null=True),
                ),
                (
                    "createdat",
                    models.DateTimeField(blank=True, db_column="CreatedAt", null=True),
                ),
                (
                    "updatedat",
                    models.DateTimeField(blank=True, db_column="UpdatedAt", null=True),
                ),
                (
                    "subscriptionid",
                    models.ForeignKey(
                        blank=True,
                        db_column="SubscriptionID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.subscriptions",
                    ),
                ),
            ],
            options={
                "db_table": "Payments",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["subscriptionid", "paymentdate"],
                        name="Payments_Subscri_748490_idx",
                    ),
                    models.Index(
                        fields=["status", "paymentdate"],
                        name="Payments_Status_7beeae_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TradingPair",
            fields=[
                (
                    "tradingpairid",
                    models.AutoField(
                        db_column="TradingPairID", primary_key=True, serialize=False
                    ),
                ),
                ("symbol", models.CharField(db_column="Symbol", max_length=20)),
                (
                    "base_currency",
                    models.CharField(db_column="BaseCurrency", max_length=10),
                ),
                (
                    "quote_currency",
                    models.CharField(db_column="QuoteCurrency", max_length=10),
                ),
                (
                    "isactive",
                    models.IntegerField(blank=True, db_column="IsActive", null=True),
                ),
                (
                    "isdeleted",
                    models.IntegerField(blank=True, db_column="IsDeleted", null=True),
                ),
                (
                    "createdby",
                    models.IntegerField(blank=True, db_column="CreatedBy", null=True),
                ),
                (
                    "updatedby",
                    models.IntegerField(blank=True, db_column="UpdatedBy", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="UpdatedAt"),
                ),
                (
                    "exchange",
                    models.ForeignKey(
                        db_column="ExchangeID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.exchange",
                    ),
                ),
            ],
            options={
                "db_table": "TradingPairs",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["base_currency"], name="TradingPair_BaseCur_dc8bb5_idx"
                    ),
                    models.Index(
                        fields=["quote_currency"], name="TradingPair_QuoteCu_43d297_idx"
                    ),
                ],
                "unique_together": {("symbol", "exchange")},
            },
        ),
        migrations.CreateModel(
            name="UserPortfolio",
            fields=[
                (
                    "portfolioid",
                    models.AutoField(
                        db_column="PortfolioID", primary_key=True, serialize=False
                    ),
                ),
                ("currency", models.CharField(db_column="Currency", max_length=10)),
                (
                    "total_amount",
                    models.DecimalField(
                        db_column="TotalAmount",
                        decimal_places=8,
                        default=0,
                        max_digits=20,
                    ),
                ),
                (
                    "available_amount",
                    models.DecimalField(
                        db_column="AvailableAmount",
                        decimal_places=8,
                        default=0,
                        max_digits=20,
                    ),
                ),
                (
                    "locked_amount",
                    models.DecimalField(
                        db_column="LockedAmount",
                        decimal_places=8,
                        default=0,
                        max_digits=20,
                    ),
                ),
                (
                    "avg_buy_price",
                    models.DecimalField(
                        blank=True,
                        db_column="AvgBuyPrice",
                        decimal_places=8,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "isactive",
                    models.IntegerField(blank=True, db_column="IsActive", null=True),
                ),
                (
                    "isdeleted",
                    models.IntegerField(blank=True, db_column="IsDeleted", null=True),
                ),
                (
                    "createdby",
                    models.IntegerField(blank=True, db_column="CreatedBy", null=True),
                ),
                (
                    "updatedby",
                    models.IntegerField(blank=True, db_column="UpdatedBy", null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="UpdatedAt"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "exchange",
                    models.ForeignKey(
                        db_column="ExchangeID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.exchange",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="UserID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.users",
                    ),
                ),
            ],
            options={
                "db_table": "UserPortfolios",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["user", "updated_at"],
                        name="UserPortfol_UserID_bff77d_idx",
                    )
                ],
                "unique_together": {("user", "exchange", "currency")},
            },
        ),
        migrations.CreateModel(
            name="UserExchangeCredentials",
            fields=[
                (
                    "credentialid",
                    models.AutoField(
                        db_column="CredentialID", primary_key=True, serialize=False
                    ),
                ),
                ("api_key", models.CharField(db_column="APIKey", max_length=500)),
                ("api_secret", models.CharField(db_column="APISecret", max_length=500)),
                (
                    "passphrase",
                    models.CharField(
                        blank=True, db_column="Passphrase", max_length=500
                    ),
                ),
                (
                    "is_testnet",
                    models.BooleanField(db_column="IsTestnet", default=True),
                ),
                (
                    "isactive",
                    models.IntegerField(blank=True, db_column="IsActive", null=True),
                ),
                (
                    "isdeleted",
                    models.IntegerField(blank=True, db_column="IsDeleted", null=True),
                ),
                (
                    "createdby",
                    models.IntegerField(blank=True, db_column="CreatedBy", null=True),
                ),
                (
                    "updatedby",
                    models.IntegerField(blank=True, db_column="UpdatedBy", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="UpdatedAt"),
                ),
                (
                    "exchange",
                    models.ForeignKey(
                        db_column="ExchangeID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.exchange",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="UserID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.users",
                    ),
                ),
            ],
            options={
                "db_table": "UserExchangeCredentials",
                "managed": True,
                "unique_together": {("user", "exchange")},
            },
        ),
        migrations.AddIndex(
            model_name="subscriptions",
            index=models.Index(
                fields=["userid", "status"], name="Subscriptio_UserID_6597d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptions",
            index=models.Index(
                fields=["enddate", "status"], name="Subscriptio_EndDate_221224_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptions",
            index=models.Index(
                fields=["status", "autorenew"], name="Subscriptio_Status_85999f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notifications",
            index=models.Index(
                fields=["userid", "isread", "createdat"],
                name="Notificatio_UserID_3e36c7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notifications",
            index=models.Index(
                fields=["type", "createdat"], name="Notificatio_Type_e2f44d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlogs",
            index=models.Index(
                fields=["userid", "createdat"], name="AuditLogs_UserID_458ea8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlogs",
            index=models.Index(
                fields=["tableaffected", "createdat"],
                name="AuditLogs_TableAf_d4039c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="apiusage",
            index=models.Index(
                fields=["user", "timestamp"], name="APIUsage_UserID_006818_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiusage",
            index=models.Index(
                fields=["exchange", "timestamp"], name="APIUsage_Exchang_accf2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylogs",
            index=models.Index(
                fields=["userid", "activitydate"], name="ActivityLog_UserID_4a64ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylogs",
            index=models.Index(
                fields=["activitytype", "activitydate"],
                name="ActivityLog_Activit_28d496_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usertrade",
            index=models.Index(
                fields=["user", "created_at"], name="UserTrades_UserID_d3d2fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usertrade",
            index=models.Index(
                fields=["exchange", "symbol"], name="UserTrades_Exchang_77bc4a_idx"
            ),
        ),
    ]
