#settings.py
"""
Django settings for this project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import sys
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import urllib.parse

# Suppress TensorFlow warnings
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'  # Suppress TF info messages

# Load environment variables from .env file
load_dotenv()

# from rest_framework_simplejwt.settings import api_settings
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

SIMPLE_JWT = {
    'ALGORITHM': 'HS256',  # Ensure this matches the token's algorithm
    'SIGNING_KEY': os.environ.get('JWT_SIGNING_KEY',SECRET_KEY),  # Use your original signing key
    'ACCESS_TOKEN_LIFETIME': timedelta(days=int(os.environ.get('JWT_ACCESS_TOKEN_LIFETIME_DAYS', 10))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.environ.get('JWT_REFRESH_TOKEN_LIFETIME_DAYS', 15))),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_CLAIM': 'user_id',
    'USER_ROLE_CLAIM': 'role',
}

STRIPE_ENABLED = os.environ.get('STRIPE_ENABLED', 'False').lower() == 'true'
#test key
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY')
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY')

# Crypto trading encryption key (store securely in production)
CRYPTO_ENCRYPTION_KEY = os.environ.get('CRYPTO_ENCRYPTION_KEY')


DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

SECURE_SSL_REDIRECT = False
# Security settings for production
if not DEBUG:
    # HTTPS Security
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Cookie Security
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    
    # Additional security headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    
    

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Model Cache Directory
MODEL_CACHE_DIR = os.path.join(BASE_DIR, 'model_cache')

# Create directory if it doesn't exist
os.makedirs(MODEL_CACHE_DIR, exist_ok=True)

STORAGES = {
    "default": {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Email Configuration from environment
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'

# URL Configuration
FRONTEND_URL = os.environ.get('FRONTEND_URL')
API_URL = os.environ.get('API_URL', 'http://localhost:8000')

ALLOWED_HOSTS = [
    'untutelar-anaya-noninferentially.ngrok-free.dev',
    'localhost',
    '127.0.0.1',
    '0.0.0.0',
]
CORS_ALLOW_ALL_ORIGINS = True  # For development only
# For development
if DEBUG:
    ALLOWED_HOSTS = ['*']  # Allow all hosts in development
    # Development CORS settings
else:
    ALLOWED_HOSTS = [
        'untutelar-anaya-noninferentially.ngrok-free.dev', # Your production domain
        'localhost',
        '127.0.0.1',
        '0.0.0.0',
    ]
    # Production CORS settings
    CORS_ALLOW_ALL_ORIGINS = False

# REDIS_HOST = os.environ.get('REDIS_HOST', 'redis') # Use 'redis' when using Docker
REDIS_HOST = 'localhost'  # Use 'localhost' for local development without Docker
REDIS_PORT_NUMBER = os.environ.get('REDIS_PORT_NUMBER', 6379)
REDIS_PASSWORD = os.environ.get('REDIS_PASSWORD')

REDIS_URL = f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT_NUMBER}"

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"{REDIS_URL}/0",
        "OPTIONS": {
            "PASSWORD": REDIS_PASSWORD,
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [f"{REDIS_URL}/1"],
            "capacity": 1000,
            "expiry": 60,
        },
    },
}

# =============================================================================
# CRYPTO TRADING CONFIGURATION
# =============================================================================

# InfluxDB Configuration
INFLUXDB_CONFIG = {
    # 'url': os.getenv('INFLUXDB_URL', 'http://influxdb:8086'), # Use 'influxdb' when using Docker
    'url': 'http://localhost:8086', # Use 'localhost' for local development without Docker
    'token': os.getenv('INFLUXDB_TOKEN'),
    'org': os.getenv('INFLUXDB_ORG'),
    'bucket': os.getenv('INFLUXDB_BUCKET'),
    'retention_days': None,  # None = infinite, or set number for days
}

MONGODB_CONFIG = {
    #'host': os.getenv('MONGO_HOST', 'localhost'), # Use 'localhost' for local development without Docker
    'host': 'localhost',  # Use 'localhost' for local development without Docker
    'port': int(os.getenv('MONGODB_PORT', 27017)),
    'database': os.getenv('MONGO_DB_NAME', 'crypto_news'),
    'username': os.getenv('MONGODB_USER'),
    'password': os.getenv('MONGODB_PASSWORD'),
    'auth_source': os.getenv('MONGO_AUTH_SOURCE', 'admin'),
    'max_pool_size': 50,
    'server_selection_timeout_ms': 5000,
    'connect_timeout_ms': 5000
}
    
from .jwt_settings import SIMPLE_JWT, SWAGGER_SETTINGS
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'configuration',
    'myapp',
    'drf_yasg', 
    'corsheaders', 
    'channels',
    'channels_redis',
    'django_celery_results',
    'django_celery_beat',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'myapp.middleware.AddCustomFieldsToHeadersMiddleware', 
    'myapp.middleware.AuthenticateUserMiddleware',
    'myapp.middleware.UserMiddleware',
    'myapp.middleware.TradingMiddleware',
    'myapp.middleware.APIRateLimitMiddleware',
]

ROOT_URLCONF = 'configuration.urls'
# Add these settings

CORS_ALLOWED_ORIGINS = [
    "https://untutelar-anaya-noninferentially.ngrok-free.dev",
    "http://untutelar-anaya-noninferentially.ngrok-free.dev",
    "https://localhost:5173",
    "http://localhost:5173",
    "http://localhost:8000",
    "http://localhost:8090",
    "http://localhost:8084",
]
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.duedoom\.com$",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    "accept",
    "authorization", 
    "content-type",
    "x-csrftoken",
    "x-requested-with",
    "origin", 
]
CSRF_TRUSTED_ORIGINS = [
    "https://untutelar-anaya-noninferentially.ngrok-free.dev",
    "http://untutelar-anaya-noninferentially.ngrok-free.dev",
    "https://localhost:5173",
    "http://localhost:5173",
    "http://localhost:8000",
    "http://localhost:8090",
    "http://localhost:8084",
]


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'configuration.wsgi.application'
ASGI_APPLICATION = 'configuration.asgi.application'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.IsUserAccess',  # Enforce authentication for APIs
    # ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'myapp.authentication.CustomJWTAuthentication',
    ],
}

 
# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get("DB_NAME"),
        'USER': os.environ.get("DB_USER"),
        'PASSWORD': os.environ.get("DB_PASSWORD"),
        # 'HOST': os.environ.get("DB_HOST"), # When using Docker, the host is the service name defined in docker-compose.yml
        'HOST': 'localhost', # Use 'localhost' for local development without Docker
        'PORT': os.environ.get("DB_PORT_NUMBER")
    },
}


STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]
# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# logging configuration 
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,  # Use stdout instead of the default stderr
            'formatter': 'verbose',
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'verbose',
        },
    },
    'formatters': {
        'verbose': {
            'format': '{asctime} {name} [{levelname}] {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{asctime} {name} {levelname} {message}',
            'style': '{',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO', 
            'propagate': True,
        },
        'celery': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'news.credibility_engine': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'news.mongo_manager': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    }
}

# Create logs directory if it doesn't exist
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =============================================================================
# CELERY CONFIGURATION
# =============================================================================

RABBITMQ_DEFAULT_USER = os.getenv('RABBITMQ_USER')
RABBITMQ_DEFAULT_PASS = os.getenv('RABBITMQ_PASSWORD')
#RABBITMQ_HOST = os.getenv('RABBITMQ_HOST') # When using Docker, the host is the service name defined in docker-compose.yml
RABBITMQ_HOST = 'localhost'  # Use 'localhost' for local development without Docker
RABBITMQ_PORT = os.getenv('RABBITMQ_PORT_NUMBER')

# Celery broker URL (Message Broker - RabbitMQ)
CELERY_BROKER_URL = f"amqp://{RABBITMQ_DEFAULT_USER}:{RABBITMQ_DEFAULT_PASS}@{RABBITMQ_HOST}:{RABBITMQ_PORT}//"

# Celery result backend (Where task results are stored - Redis)
CELERY_RESULT_BACKEND = f"{REDIS_URL}/2"

# Alternative naming (some versions use this)
CELERY_BACKEND = CELERY_RESULT_BACKEND

# Optional: Celery cache backend (For caching task results - Redis)
CELERY_CACHE_BACKEND = f"{REDIS_URL}/3"   # Different DB for Celery cache

# Basic Celery settings
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True

# Task result settings
CELERY_RESULT_EXPIRES = 3600  # Results expire after 1 hour
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 300  # 5 minutes max per task
CELERY_TASK_SOFT_TIME_LIMIT = 240  # 4 minutes soft limit

# Worker settings
CELERY_WORKER_CONCURRENCY = 4
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000
CELERY_WORKER_DISABLE_RATE_LIMITS = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# Beat scheduler
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Add Celery Beat Schedule 
from celery.schedules import crontab
    
CELERY_BEAT_SCHEDULE = {
    'initialize-series-configs': {
        'task': 'myapp.tasks.series_tasks.initialize_series_configs',
        'schedule': crontab(hour=0, minute=0),  # Daily at midnight
        'options': {'queue': 'maintenance'}
    },
    'detect-and-report-gaps': {
        'task': 'myapp.tasks.series_tasks.detect_and_report_gaps',
        'schedule': 3600.0,  # Every hour
        'options': {'queue': 'maintenance'}
    },
    'monitor-series-health': {
        'task': 'myapp.tasks.series_tasks.monitor_series_health',
        'schedule': 300.0,  # Every 5 minutes
        'options': {'queue': 'maintenance'}
    },
    'comprehensive-content-update': {
        'task': 'myapp.tasks.content_tasks.comprehensive_content_update',
        'schedule': crontab(minute=0, hour='*/6'),  # Every 6 hours
    },
    'scheduled-content-fetch': {
        'task': 'myapp.tasks.content_tasks.scheduled_content_fetch',
        'schedule': crontab(minute=0, hour='*/2'),  # Every 2 hours
    },
    
    # Topic modeling tasks
    'update-topic-model': {
        'task': 'myapp.tasks.content_tasks.update_topic_model',
        'schedule': crontab(minute=0, hour=4),  # 4 AM daily
    },
    'detect-trending-topics': {
        'task': 'myapp.tasks.content_tasks.detect_trending_topics',
        'schedule': crontab(minute=0, hour='*'),  # Every hour
    },
    'assign-topics-to-new-content': {
        'task': 'myapp.tasks.content_tasks.assign_topics_to_new_content',
        'schedule': crontab(minute=30, hour='*'),  # Every hour at :30
    },
    'persist-trending-data': {
        'task': 'myapp.tasks.content_tasks.persist_trending_data',
        'schedule': crontab(minute=0, hour='*'),  # Every hour
    },
    
    # RAG System Tasks
    'rag-scheduled-index-update': {
        'task': 'myapp.tasks.rag_tasks.scheduled_index_update',
        'schedule': crontab(minute=15, hour='*/6'),  # Every 6 hours at :15
        'args': (6, 5.0),
    },
    'rag-daily-full-reindex': {
        'task': 'myapp.tasks.rag_tasks.daily_full_reindex',
        'schedule': crontab(minute=0, hour=3),  # 3 AM daily
        'args': (7, 4.0),
    },
    'rag-cache-cleanup': {
        'task': 'myapp.tasks.rag_tasks.cleanup_rag_cache',
        'schedule': crontab(minute=0, hour=0),  # Midnight
    },
    
    # Maintenance tasks
    'cleanup-old-api-usage': {
        'task': 'myapp.tasks.content_tasks.cleanup_old_api_usage',
        'schedule': crontab(minute=0, hour=2),  # 2 AM daily
    },
}

# Queue configuration for better task routing
CELERY_TASK_ROUTES = {
    #'myapp.tasks.series_tasks.run_series_orchestrator': {'queue': 'trading'},
    'myapp.tasks.series_tasks.initialize_series_configs': {'queue': 'maintenance'}, 
    'myapp.tasks.series_tasks.detect_and_report_gaps': {'queue': 'maintenance'},
    'myapp.tasks.series_tasks.monitor_series_health': {'queue': 'maintenance'},
    'myapp.tasks.content_tasks.comprehensive_content_update': {'queue': 'content'},
    'myapp.tasks.content_tasks.scheduled_content_fetch': {'queue': 'content'},
    'myapp.tasks.content_tasks.fetch_and_process_social_posts': {'queue': 'content'},
    'myapp.tasks.tasks.cleanup_old_api_usage': {'queue': 'maintenance'},
    
} 

# RAG Configuration
RAG_EMBEDDING_MODEL = os.getenv('RAG_EMBEDDING_MODEL', 'sentence-transformers/all-mpnet-base-v2')
RAG_LLM_MODEL = os.getenv('RAG_LLM_MODEL', 'llama3.1')
LLM_PRIMARY_PROVIDER = os.getenv('LLM_PRIMARY_PROVIDER', 'ollama')

# API Keys (from environment)
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY')
GROQ_API_KEY = os.getenv('GROQ_API_KEY')

# Ollama (local)
OLLAMA_BASE_URL = os.getenv('OLLAMA_BASE_URL', 'http://192.168.1.17:11434')


# WebSocket Configuration
WEBSOCKET_CONFIG = {
    'enabled': os.getenv('WEBSOCKET_ENABLED', 'True').lower() == 'true',
    'max_connections_per_user': int(os.getenv('MAX_WEBSOCKET_CONNECTIONS', 5)),
    'heartbeat_interval': int(os.getenv('WEBSOCKET_HEARTBEAT', 30)),
    'price_update_interval': 2,  # seconds
    'portfolio_update_interval': 5,  # seconds
}

TRADING_CONFIG = {
    # Series configuration
    'MAX_SERIES_PER_WORKER': 500,
    'DEFAULT_SHARD_COUNT': 3,
    'BACKFILL_BATCH_SIZE': 1000,
    
    # Timeframe settings
    'SUPPORTED_TIMEFRAMES': ['1h', '1d'], #'1m', '5m', '15m', '30m', , '2h', '4h', '6h', '12h',  '3d',
    'PRIORITY_TIMEFRAMES': ['1h'],  # Process these first
    
    # Probing configuration
    'MAX_PROBE_ATTEMPTS': 3,
    'PROBE_INITIAL_WINDOW_DAYS': 730,  # 2 years
    'PROBE_MAX_STEPS': 20,
    
    # Rate limiting
    'DEFAULT_RATE_LIMIT_MS': 1000,
    'EXCHANGE_RATE_LIMITS': {
        'binance': 100,    # 10 requests per second
        'okx': 200,        # 5 requests per second  
        'coinbase': 300,   # 3.33 requests per second
        'kraken': 1000,    # 1 request per second
    },
    
    # Gap detection
    'GAP_DETECTION_ENABLED': True,
    'GAP_SCAN_INTERVAL': 3600,  # Scan every hour (in seconds)
    
    # Monitoring
    'HEALTH_CHECK_INTERVAL_SECONDS': 300,  # 5 minutes
    'STALE_DATA_THRESHOLD_MULTIPLIER': 3,  # 3x timeframe
    'WORKER_HEARTBEAT_TIMEOUT_SECONDS': 300,
    
    # Error handling
    'MAX_CONSECUTIVE_FAILURES': 5,
    'EXPONENTIAL_BACKOFF_MAX_SECONDS': 300,
    'GRACEFUL_DEGRADATION_STEPS': ['1d', '3d', '7d'],  # Nudge steps
}

LOGGING['loggers']['trading'] = {
    'handlers': ['console', 'file'],
    'level': 'INFO',
    'propagate': False,
}
# Add to your existing LOGGING configuration
LOGGING['loggers']['channels'] = {
    'handlers': ['console', 'file'],
    'level': 'DEBUG',
    'propagate': False,
}
# Add more detailed logging for WebSocket debugging
LOGGING['loggers']['myapp.consumers'] = {
    'handlers': ['console', 'file'],
    'level': 'DEBUG',  # Change to DEBUG for more detailed logs
    'propagate': False,
}

# Add channels specific logging
LOGGING['loggers']['channels.consumer'] = {
    'handlers': ['console', 'file'],
    'level': 'DEBUG',
    'propagate': False,
}

LOGGING['loggers']['channels.layers'] = {
    'handlers': ['console', 'file'],
    'level': 'DEBUG',
    'propagate': False,
}
LOGGING['loggers']['myapp.series_orchestrator'] = {
    'handlers': ['console', 'file'],
    'level': 'DEBUG',  # Change to DEBUG for detailed logs
    'propagate': False,
}

LOGGING['loggers']['myapp'] = {
    'handlers': ['console', 'file'],
    'level': 'DEBUG',  # or 'INFO'
    'propagate': True,
}

APPEND_SLASH = False